### ISSUE TITLE
On Mac: Settings Window don't close

### ISSUE THREAD

**Issue by schleif** [autocrypt-thunderbird/autocrypt-thunderbird#1]
At the moment I close Thunderbird and have the settings window open. It doesn't close like the others.

**Comment by Valodim** [comment]
Thanks for your report!

There are two ways to open the settings, either via Addons -> Autocrypt, or Preferences -> Autocrypt. Does this happen for both of them?

**Comment by schleif** [comment]
Nope, it's appearing in case of Addons -> Autocrypt. The other way opens an integrated windows. Its lifetime is bind to main window's lifetime.
