### ISSUE TITLE
Thunderbird will have native OpenPGP

### ISSUE THREAD

**Issue by brenthuisman** [autocrypt-thunderbird/autocrypt-thunderbird#10]
The blogpost indicates more than simply bundling OpenPGP.js and calling it a day: it is not sure if WoT will evne be implemented (like this plugin does not). https://blog.mozilla.org/thunderbird/2019/10/thunderbird-enigmail-and-openpgp/

Perhaps worth getting in touch with them? Or perhaps you are in fact already involved ;)

**Comment by Valodim** [comment]
I was aware, thanks :) This is a fairly experimental extension, but I'm hoping some of the ideas from this extension will reach broader adoption. We'll see how that goes.

**Comment by brenthuisman** [comment]
Seems like they are going for 'classic Enigmail' (see bottom of message):
https://mail.mozilla.org/pipermail/tb-planning/2019-December/007292.html
And "Short answer: Thunderbird's implementation will use an approach that is
different from some of the recommendations made in the Autocrypt
specification":
https://mail.mozilla.org/pipermail/tb-planning/2019-December/007293.html

Pity.
