### ISSUE TITLE
Make it easier to import an existing key

### ISSUE THREAD

**Issue by ladiko** [autocrypt-thunderbird/autocrypt-thunderbird#14]
Hello,

I dont want to generate a new PGP key rather than using my existing one. I can't find any way to import an existing key.

Thanks in advance.

**Comment by ddelabru** [comment]
My understanding is that the current workflow for this is to first let Autocrypt generate a key, then:

1. Open "Autocrypt settings" (in Thunderbird's "Edit" menu)
2. Click "Manage"
3. Click "Import" and select a file such as the files you can generate with `gpg -a --export-private-keys`. This won't work if you have the Enigmail extension installed, even if it's disabled
4. Return to the main Autocrypt settings dialog and click the "Setup" button next to the Status of Autocrypt configuration for your email address
5. Choose "Use a different key" in the setup dialog and select the correct key fingerprint from the dropdown menu

After these steps, you can return to the "Manage" dialog to delete the key that Autocrypt generated if you wish.

**Comment by Valodim** [comment]
The description from @ddelabru is the way to handle this, so far. Thanks for writing it up.

This is a bit of an underdeveloped workflow in the extension, sorry about that :) I considered adding a way to import directly from gnupg, since there is a fairly large audience with that background.
