### ISSUE TITLE
"Autocrypt" button doesn't show up in compose dialog

### ISSUE THREAD

**Issue by dkg** [autocrypt-thunderbird/autocrypt-thunderbird#15]
a friend uninstalled enigmail on thunderbird and installed the autocrypt plugin on Ubuntu.  I sent them signed (but not-encrypted) mail with an `Autocrypt` header that should have allowed them to encrypt.

When they reply, their message composition window does not appear to offer them a chance to encrypt:

![pngout](https://user-images.githubusercontent.com/66738/69991248-599a4380-1515-11ea-9cb6-4fb0264ac3b6.png)

it would be great to publish a screenshot that shows how this is *supposed* to look at least, but i don't see anything.  Do they need to do anything else to get the button to appear?

when they send me (unencrypted) mail, that mail *does* have an `Autocrypt:` header, so i know that the extension is installed.

**Comment by Valodim** [comment]
> it would be great to publish a screenshot that shows how this is supposed to look at least, but i don't see anything. Do they need to do anything else to get the button to appear?

There should be a button like this 
![image](https://user-images.githubusercontent.com/27813/69991899-d98dd100-1548-11ea-830c-350ffa75f7e3.png)
in the button bar up top, by default it's placed right to the "Save" button.

Can you right-click the button bar, select "Customize" and check if there is an Autocrypt button in the dialog? If so, that one can be dragged onto the bar.

Apart from that, in the in the dropdown from the burger button in the main view, is there an "Autocrypt Settings" menu item?

Could be something went wrong during installation or initialization of the extension. Thunderbird and XUL work in very mysterious ways sometimes.

**Comment by dsgiigh** [comment]
Hi -- this is my bug. No Autocrypt button in "customize" -- nor an Autocrypt Settings from the burger button. 

However, I do find Autocrypt settings in Edit menu. Want a screenshot of what I see when I launch those settings? Anything I should redact if so?

**Comment by Valodim** [comment]
Ah, sorry I meant "Autocrypt Settings" in Preferences from the burger button menu

It seems that, for some reason, parts of the UI aren't correctly initialized. Can you say what version of Thunderbird you're using, and if you have any other extensions installed? Perhaps there are conflicts? (I wonder if it's the dark theme? I never actually tested with that)

**Comment by dsgiigh** [comment]
Yes, it's there and brings up the same settings box as doing it from Edit/Autocrypt Settings. I'm using Ubuntu 18.04.3; Thunderbird 68.2.1 (64-bit). The only other add-on, which must be a Mozilla default since I don't recognize it, is "FileLink for WeTransfer". 

I had Enigmail installed but deleted it before installing Autocrypt. I did reinstall Enigmail briefly, to create a new key (mine had expired so I revoked it), but have removed it again.

UPDATE: It didn't work before I reinstalled Enigmail or afterward.

**Comment by Valodim** [comment]
Sorry, I have no idea how to debug or reproduce this :(

If someone can reproduce this who is knowledgable about Thunderbird debugging, I'd appreciate a hand.

**Comment by cloudnine-gjacob** [comment]
I'm having a similar problem I can see the icons under customize and i can drag them up but when i reopen the compose window the next time they are gone again.

![Screenshot 2020-05-01 at 15 13 01](https://user-images.githubusercontent.com/7857645/80807760-496abb00-8bbe-11ea-9651-078939590834.png)
![Screenshot 2020-05-01 at 15 09 59](https://user-images.githubusercontent.com/7857645/80807766-4d96d880-8bbe-11ea-93a6-033af52af614.png)
![Screenshot 2020-05-01 at 15 10 12](https://user-images.githubusercontent.com/7857645/80807769-4ec80580-8bbe-11ea-9baf-fddaa8c267a5.png)
