### ISSUE TITLE
Optionally sign unencrypted emails [feature request]

### ISSUE THREAD

**Issue by ddelabru** [autocrypt-thunderbird/autocrypt-thunderbird#16]
Although one of the desirable features of Autocrypt is that it works without email attachments that might confuse recipients, it is still sometimes useful to sign an unencrypted email—for example, when using a public mailing list where it is commonplace to sign messages. For cases like these it would be useful to allow the user to enable signing of unencrypted emails on a per-message basis.

**Comment by Valodim** [comment]
> it is still sometimes useful to sign an unencrypted email—for example, when using a public mailing list where it is commonplace to sign messages

To what end, though? Signing messages is not an end in itself, and people don't generally doubt messages are from who they say they are. It's also impossible to explain what an email signature really is and what it does, which makes any kind of "sign message" button a source of confusion at best, subtle anxiety at worst.

I wrote down some thoughts on this a few years ago from K-9 Mail's perspective: https://k9mail.app/2016/11/24/OpenPGP-Considerations-Part-I.html

Either way, this definitely isn't a use case we want to support in Autocrypt. Sorry :)

**Comment by ddelabru** [comment]
I totally understand the case against this for general use. I think the motivation for having it available is to fit very specific (cultural?) contexts but if that significantly complicates everyday adoption than it's reasonable to leave it out.
