### ISSUE TITLE
Backup Key: Message dialog hard to understand

### ISSUE THREAD

**Issue by dorleosterode** [autocrypt-thunderbird/autocrypt-thunderbird#17]
I'm using thunderbird version 68.5 with the autocrypt-plugin version 0.9.3.

When I make a backup of my key, the key is stored in an encrypted pgp message and the password for decrypting is shown in an dialog. The first time I made a backup, I didn't understand that the number in the dialog is the actual password for the backup, so I didn't save it.

This could be prevented, when the text in the dialog is more meaningful. Until now the text is only "Ok:" followed by the password. Something like "This is the password for your backup and you should save it somewhere safe" would be helpful :)

**Comment by Valodim** [comment]
Yup, makes sense :+1: PRs welcome, otherwise I'll try to find some time in the next few days.

**Comment by roel1975** [comment]
Does it mean that I can still use the 2fa key?
