### ISSUE TITLE
BCC error message on non configured mailbox

### ISSUE THREAD

**Issue by g6094199** [autocrypt-thunderbird/autocrypt-thunderbird#18]
Hi,

i have a non autocrypt configured mailbox:

![Bildschirmfoto vom 2020-03-05 12-28-15](https://user-images.githubusercontent.com/37833326/75977785-6ac06b00-5edd-11ea-993c-fce88d8740e8.png)

in a multi mailbox configured TB.

When i try to send BCC only messages from this box i get the following error:

![Bildschirmfoto vom 2020-02-03 20-24-49](https://user-images.githubusercontent.com/37833326/75977643-2765fc80-5edd-11ea-87a9-47fe4d68ca46.png)

This error can be ignored but it should not pop up on unconfigired mailboxes!

Sash

**Comment by Valodim** [comment]
Sounds like a bug. Thanks for reporting, I'll see if I can get it fixed :)
