### ISSUE TITLE
Thunderbird can't send emails encrypted with Autocrypt

### ISSUE THREAD

**Issue by brenthuisman** [autocrypt-thunderbird/autocrypt-thunderbird#19]
I was just trying to send a encrypted message since a while (two weeks?) and Thunderbird pops up a very generic 'can't send' message. Set Autocrypt to not encrypt and it sends fine. Tested this on TB 68.4.2 and 68.6 on Windows and 68.4.1 on Linux, different profiles/accounts, all show this issue.

A screenshot of the TB error console seems to show a relevant problem:

![image](https://user-images.githubusercontent.com/2943652/76777091-fb356000-67a7-11ea-83ed-184f07d1f873.png)

Not sure if an update in TB caused this (I think it used to work well on 68.4.something), but in any case it's a bit of a showstopper ;)

**Comment by brenthuisman** [comment]
I'll have to correct myself a bit: it have narrowed this error down to sending through a particular smtp server, and not through another one. I can't seem to find much relevant in the log, if I can help you troubleshoot let me know.

**Comment by schleif** [comment]
I've experienced this a few times. But couldn't find a reason nor reproducing steps.

**Comment by brenthuisman** [comment]
Still have this, with a specific server only.
