### ISSUE TITLE
Manage dialog does not respect locale settings

### ISSUE THREAD

**Issue by puzzlewolf** [autocrypt-thunderbird/autocrypt-thunderbird#2]
In preferences / manage, the dates do not respect locale settings. 
Expected: `09.04.2019` (german locale)
Actual: `9/4/2019`

Thunderbird Preferences / Advanced / Date and Time Formatting is set to `Regional settings locale: German (Germany)`

**Comment by Valodim** [comment]
fixed, will be included in next release
