### ISSUE TITLE
Link to issue tracker in description

### ISSUE THREAD

**Issue by puzzlewolf** [autocrypt-thunderbird/autocrypt-thunderbird#5]
The description on https://addons.thunderbird.net/thunderbird/addon/autocrypt/ actually contains the link. But it is missing in the details page in Add-ons Manager / Extensions.

**Comment by Valodim** [comment]
Hm, it seems that Thunderbird doesn't render links on that page. Not sure I can change anythinga bout that? If anyone knows an extension that does this, please leave me a note
