### ISSUE TITLE
Autocrypt Setup Message: import key not working

### ISSUE THREAD

**Issue by ghost** [autocrypt-thunderbird/autocrypt-thunderbird#6]
Hi,

just playing around with your new add-on! Great experience overall. But I couldn't get it to import my key from an Autocrypt Setup Message (ASM), neither from Delta-Android, nor Delta-Desktop, nor Thunderbird + Enigmail.

## Expected Behavior

I send an ASM from a different autocrypt-compliant client, I click on import in Thunderbird, it shows me an input for the setup code, I enter the setup code, it shows a "successful" message, it imports the key. When I then message bot@autocrypt.org, it replies with the fingerprint of the imported key.

## Actual Behavior

I send an ASM from a different autocrypt-compliant client, I click on import in Thunderbird, it shows me an input for the setup code, I enter the setup code, it shows a "successful" message, but doesn't import the key (with an ASM from delta desktop 0.104.0, it doesn't even show the confirmation message). When I then message bot@autocrypt.org, it replies with the fingerprint of the old key. It also shows the fingerprint of the old key in the Autocrypt settings.

## Steps to Reproduce

1. Initiate an ASM from DeltaChat Android, see the setup code
2. Click "Run setup from message" in Thunderbird
3. Enter the setup code
4. See the confirmation message, click on "Ok"
5. Send a mail to bot@autocrypt.org
6. See the old Fingerprint in the Mail at "found peeraddr="

## Versions

**OS:** Xubuntu 18.04  
**Thunderbird Version:** 68.1.0
**Autocrypt-Thunderbird Version:** 0.9.1.6

**Comment by Valodim** [comment]
Hey, thanks for testing and reporting!

Can you check if the key was actually imported? That is, whether it is listed under `Autocrypt Settings` -> `Manage`? I think I just fail to change the active key on import.

**Comment by ghost** [comment]
Yes, it was :) that part worked. I didn't find a way to set it active manually though.

**Comment by Valodim** [comment]
It's under the `Run Setup` button. That one is severely mislabeled, but in the latest (still in review) version changed to just `Setup`.

I think it's important to have a notion of "Archived" keys, which are used for decryption but not otherwise. I think I'll add a dialog on import asking the user whether a key should be actively used, or just archived so messages to it can be read.

**Comment by ghost** [comment]
Sounds good :) Stumbled over the "Run Setup" vs. "Send Setup Message" as well. What do you think about "Setup on this device" instead of "Run Setup"? vs. "Setup for other device: Send Setup Message"?

**Comment by Valodim** [comment]
Sounds kinda longish, doesn't it? I had thought that the distinction might be clear enough between "Setup" and "Setup for other device". Anyways, it's in the version that's in the pipeline, I'll just wait to hear if anyone is confused about it :)

**Comment by ghost** [comment]
Hm, I was already confused, because I opened the settings to send an Autocrypt Setup Message and wasn't aware that I even could trigger a manual Setup for this local device. Only when I read the whole settings window, I realized that sending an ASM was somewhere completely else.

btw, sending an ASM didn't work for me either; the message was sent, but it didn't show the setup code, so I couldn't type it in on the other device.

**Comment by Valodim** [comment]
> Only when I read the whole settings window, I realized that sending an ASM was somewhere completely else.

I don't understand. There are literally only two buttons in the settings, one for sending a setup message, one for changing the local setup. What do you mean by "somewhere completely else"?

> btw, sending an ASM didn't work for me either; the message was sent, but it didn't show the setup code, so I couldn't type it in on the other device.

That's another change that's queued in the review process. It's not finished, but at least it shows the message. (I gotta say it is a bit annoying that it takes a week a more every time until releases actually land :hurtrealbad:)

**Comment by ghost** [comment]
> > Only when I read the whole settings window, I realized that sending an ASM was somewhere completely else.
> 
> I don't understand. There are literally only two buttons in the settings, one for sending a setup message, one for changing the local setup. What do you mean by "somewhere completely else"?

That's exactly what I meant with somewhere completely else :D I didn't find it at first glance, because my eyes can only look at one button at the same time ;) at the 2nd or 3rd glance I found it of course. 

But when I look for a setup message and I find a button saying "setup" on first glance, I click it ;)

> > btw, sending an ASM didn't work for me either; the message was sent, but it didn't show the setup code, so I couldn't type it in on the other device.
> 
> That's another change that's queued in the review process. It's not finished, but at least it shows the message. (I gotta say it is a bit annoying that it takes a week a more every time until releases actually land :hurtrealbad:)

Okay, then I don't need to open an issue for it :D that's what I wanted to know. Great software btw! Just included it on autocrypt.org/dev-status.html :)

**Comment by LanceHaverkamp** [comment]
@Valodim
Since selecting an archived key does not work yet; how do I delete all record of an archived key, in Windows?   ...so when I delete the key, then re-import it; the plugin doesn't remember that it's archived--and prevent me from selecting it?

**Comment by Valodim** [comment]
>  ...so when I delete the key, then re-import it; the plugin doesn't remember that it's archived--and prevent me from selecting it?

Come again? An archived key is just one that isn't currently in active use for any identity. You should be able to select it, when you click "Setup" in the settings dialog. Note that you can't use a key for an identity that does not have a corresponding user id.

Hmm. I wonder if "inactive" would be better wording for this?

**Comment by LanceHaverkamp** [comment]
@Valodim 
> You should be able to select it, when you click "Setup" in the settings dialog.

This shows 5 keys, 3 of which are for my personal email:
![1](https://user-images.githubusercontent.com/15806629/66092071-b6927100-e547-11e9-9a1a-bd642cc88e67.jpg)

But when I go to setup > use a different key, you can see that there are no keys listed from which to choose--just generate a new key: 
![2](https://user-images.githubusercontent.com/15806629/66092080-be521580-e547-11e9-95c2-3cadd9d0cc4c.jpg)
