### ISSUE TITLE
Unknown sender: Autocrypt status: Encrypted transport only

### ISSUE THREAD

**Issue by brenthuisman** [autocrypt-thunderbird/autocrypt-thunderbird#7]
I just setup the plugin using a fresh 68.1 Thunderbird tarball and fresh profile. I noticed that an older message that had been sent signed and encrypted was labelled as encrypted transport only. After retrieving that senders key, did the Autocrypt label on the older message light up green saying end-to-end encrypted. Would is be clearer to say something like 'Cannot verify validity of senders key/signature, would you like to retrieve it?'

**Comment by Valodim** [comment]
> Would is be clearer to say something like 'Cannot verify validity of senders key/signature, would you like to retrieve it?'

This error message requires a *vast* amount of knowledge to know what each of the pieces of that statement mean. What's a signature, and how is it valid or invalid? How is a key valid or invalid? Why is it even missing, I just received this message didn't I? Retrieve, how and from where? What difference does it even make, I can read the message just fine can't I?

This is a really difficult issue you bring up, and there's no straightforward answer.  I'd like to avoid workflows where we effectively train the user to hit that one button to make the issue go away, it ends up the same thing as doing it automatically except the responsibility is slightly fuzzier. So if we wanted to have a feature like that, I'd automate the lookup.

Hmm. I'll have to think some more about this

**Comment by brenthuisman** [comment]
If I can read an E2EE message just fine and having the senders key in db is a detail, then you can show the green label confirming E2EE. I agree, knowing the user doesn't have to (and maybe shouldn't) matter, but right now, it does.
